FAIL
Kernel panic in run: PANIC at ../../threads/synch.c:254 in lock_release(): assertion `lock_held_by_current_thread (lock)' failed.
Call stack: 0x8004214774 0x800420ae33 0x800421fd9b 0x800421e34c 0x800421ab30 0x800421a2ec 0x800421a03c 0x400567 0x4007f7 0x400107 0x401504 0x40154d
Translation of call stack:
0x0000008004214774: debug_panic (lib/kernel/debug.c:32)
0x000000800420ae33: lock_release (threads/synch.c:256)
0x000000800421fd9b: inode_read_at (filesys/inode.c:278)
0x000000800421e34c: file_read (filesys/file.c:73)
0x000000800421ab30: read (userprog/syscall.c:311)
0x000000800421a2ec: syscall_handler (userprog/syscall.c:102)
0x000000800421a03c: no_sti (userprog/syscall-entry.o:?)
0x0000000000400567: (unknown)
0x00000000004007f7: (unknown)
0x0000000000400107: (unknown)
0x0000000000401504: (unknown)
0x000000000040154d: (unknown)
